Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.box_version = "4.3.12"

  NODES = {
    "AMKUBDEVRKEN01A" => "10.98.72.101",
    "AMKUBDEVRKEN01B" => "10.98.72.102",
    "AMKUBDEVRKEN02A" => "10.98.72.103"
  }

  NODES.each do |name, ip|
    config.vm.define name do |node|
      node.vm.hostname = name
      node.vm.network "private_network", ip: ip
      node.vm.provider "libvirt" do |lv|
        lv.memory = 4096
        lv.cpus = 2
        lv.storage :file, size: '60G', type: 'qcow2', bus: 'virtio'
      end
      node.vm.provision "shell", inline: <<-SHELL
        echo "Verificando discos conectados:"
        lsblk
      SHELL
      # Provisión de Ansible con playbook específico para cada nodo
      node.vm.provision "ansible" do |ansible|
        ansible.playbook = "../Ansible/Playbooks/playbook-#{name}.yml"
        ansible.become = true
        ansible.inventory_path = "../Ansible/inventory/vagrant_ansible_inventory"
        ansible.limit = name
      end
    end
  end
end