- name: Configurar nodo master AMKUBDEVRKEN01B para RKE2
  hosts: all
  become: yes
  tasks:
    - name: Actualizar lista de paquetes
      apt:
        update_cache: yes
      changed_when: false

    - name: Instalar dependencias necesarias
      apt:
        name:
          - curl
          - iptables
          - apparmor
        state: present

    - name: Descargar script de instalación de RKE2
      get_url:
        url: https://get.rke2.io
        dest: /tmp/install-rke2.sh
        mode: '0755'

    - name: Instalar RKE2 server
      command: /tmp/install-rke2.sh
      args:
        creates: /usr/local/bin/rke2

    - name: Crear directorio de configuración para RKE2
      file:
        path: /etc/rancher/rke2
        state: directory
        mode: '0755'

    - name: Crear archivo config.yaml para RKE2
      copy:
        content: |
          server: https://10.98.72.101:9345
          token: adan
          node-name: master-3
          tls-san:
            - 10.98.72.103
            - AMKUBDEVRKEN02A
        dest: /etc/rancher/rke2/config.yaml
        mode: '0644'

    - name: Habilitar y arrancar el servicio de RKE2 server
      systemd:
        name: rke2-server
        enabled: yes
        state: started

    - name: Esperar a que el nodo esté listo
      command: /usr/local/bin/rke2 kubectl get nodes
      register: kubectl_nodes
      retries: 30
      delay: 10
      until: kubectl_nodes.rc == 0
      changed_when: false

    - name: Configurar acceso a kubectl para el usuario vagrant
      copy:
        src: /etc/rancher/rke2/rke2.yaml
        dest: /home/vagrant/.kube/config
        owner: vagrant
        group: vagrant
        mode: '0600'
        remote_src: yes

    - name: Actualizar KUBECONFIG para el usuario vagrant
      lineinfile:
        path: /home/vagrant/.bashrc
        line: 'export KUBECONFIG=/home/vagrant/.kube/config'
        state: present